{{- if .Values.ingress.enabled -}}
{{- $fullName := include "gitbucket.fullname" . -}}
{{- $servicePort := .Values.service.port -}}
{{- $ingressPath := .Values.ingress.path -}}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.Version -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.Version -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    app: {{ template "gitbucket.name" . }}
    chart: {{ template "gitbucket.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
{{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- range .Values.ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
          - path: {{ $ingressPath }}
            backend:
              {{ if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.Version -}}
              service:
                name: {{ $fullName }}
                port:
                  name: http
              {{- else -}}
              serviceName: {{ $fullName }}
              servicePort: http
              {{- end }}
            {{ if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.Version -}}
            pathType: ImplementationSpecific
            {{- end }}
  {{- end }}
{{- end }}
